126-stories and tips padding issue fix and added null condition for s…
hlxsites/fonterra-fernleaf pull request #137
Opened 2023-08-17 12:47 UTC by ParthasharathiB

…plash image

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #126

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/en
- After: https://126-storiesandtips--fonterra-fernleaf--hlxsites.hlx.page/en

2023-08-17 16:16 UTC, sselvara requested changes

2023-08-17 16:16 UTC, sselvara commented on blocks/story-list/story-list.css
> +  color: #00338d;
create a color variable.

2023-08-17 16:16 UTC, sselvara commented on styles/styles.css
> +.story-tips .default-content-wrapper {
pull the code from main and test this pls.

2023-08-17 16:16 UTC, sselvara commented on styles/styles.css
> +  .story-tips .story-tips-action {
pull the code from main and test this pls.

2023-08-18 13:40 UTC, sselvara approved these changes

2023-08-18 14:26 UTC, mkbansal1 approved these changes

2023-08-21 06:22 UTC, merged