162-Add bg image at bottom of recipes listing page.
hlxsites/fonterra-fernleaf pull request #186
Opened 2023-08-22 13:53 UTC by ParthasharathiB

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #162

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/en
- After: https://162-bottom-bg--fonterra-fernleaf--hlxsites.hlx.page/en

2023-08-22 14:08 UTC, mkbansal1 requested changes
Please hold this PR until another cleanup PR get merged
https://github.com/hlxsites/fonterra-fernleaf/pull/182

2023-08-22 14:17 UTC, mkbansal1 commented on blocks/recipe-list/recipe-list.js
> +} from '../../scripts/delayed.js';
`formPictureTag `is moved in scripts.js

2023-08-22 14:20 UTC, mkbansal1 requested changes
@ParthasharathiB  

1. Please take the latest from the main and resolve conflicts
2. Why bg images are set at 2 places (delayed.js & recipe-list.js)?

2023-08-23 04:51 UTC, sselvara approved these changes

2023-08-23 04:54 UTC, sselvara approved these changes

2023-08-23 04:57 UTC, merged