Bg image issue fix
hlxsites/fonterra-fernleaf pull request #225
Opened 2023-09-01 04:58 UTC by ParthasharathiB

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #219, #214

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/
- After: https://219-calciyum-bgimg--fonterra-fernleaf--hlxsites.hlx.live/en/products/calciyum

2023-09-01 06:12 UTC, asthabh23 commented
I see CLS on stories-and-tips page:
https://pagespeed.web.dev/analysis/https-219-calciyum-bgimg--fonterra-fernleaf--hlxsites-hlx-live-en-stories-and-tips/c15715rqbc?form_factor=mobile

2023-09-01 16:58 UTC, sselvara commented
@ParthasharathiB Mobile performance is dropped for calciyum page https://pagespeed.web.dev/analysis/https-219-calciyum-bgimg--fonterra-fernleaf--hlxsites-hlx-live-en-products-calciyum/zo1xk8ch2r?form_factor=mobile.

2023-09-04 04:49 UTC, ParthasharathiB commented
@sselvara  can you please check again i can see 100% https://pagespeed.web.dev/analysis/https-219-calciyum-bgimg--fonterra-fernleaf--hlxsites-hlx-live-en-products-calciyum/zcqfnxlm3e?form_factor=mobile

2023-09-04 14:35 UTC, sselvara requested changes

2023-09-04 14:35 UTC, sselvara commented on blocks/story-list/story-list.js
> +  setTimeout(() => {
use same syntax window.setTimeout

2023-09-04 15:48 UTC, sselvara approved these changes

2023-09-04 16:13 UTC, merged