54 hero section update
hlxsites/fonterra-fernleaf pull request #58
Opened 2023-08-01 19:42 UTC by noormd08

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #54 

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/
- After: https://54-hero-section-update--fonterra-fernleaf--hlxsites.hlx.page/en/full-width-banner

2023-08-02 04:34 UTC, mkbansal1 requested changes
@noormd08 

- Content is overlapped initially
<img width="865" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/ff07d39e-5146-410f-a9ce-9b42880a4402">

- Image paths are added as data-attribute in the section tag but instead of using a background image, a picture tag image is used. due to this, image is taking full height
<img width="667" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/846e9787-dce8-485a-846c-7551eb27bd55">
<img width="441" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/95ec62c4-d213-45d6-8135-a29b4c512b4f">

- CLS score is low, i believe it will get fixed once you handle above point (we actually do not need picture tag here)
![image](https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/55adcdcc-a468-4c90-9721-a33ad8f0a930)

2023-08-02 04:37 UTC, mkbansal1 commented on scripts/delayed.js
> +function GenerateBackGroundImages() {
Change method name to `generateBackgroundImages`

2023-08-02 16:26 UTC, noormd08 commented
> @noormd08
> 
> * Content is overlapped initially
> 
> <img alt="image" width="865" src="https://user-images.githubusercontent.com/129100763/257700054-ff07d39e-5146-410f-a9ce-9b42880a4402.png">
> * Image paths are added as data-attribute in the section tag but instead of using a background image, a picture tag image is used. due to this, image is taking full height
> 
> <img alt="image" width="667" src="https://user-images.githubusercontent.com/129100763/257700256-846e9787-dce8-485a-846c-7551eb27bd55.png"> <img alt="image" width="441" src="https://user-images.githubusercontent.com/129100763/257700876-95ec62c4-d213-45d6-8135-a29b4c512b4f.png">
> * CLS score is low, i believe it will get fixed once you handle above point (we actually do not need picture tag here)
>   ![image](https://user-images.githubusercontent.com/129100763/257702415-55adcdcc-a468-4c90-9721-a33ad8f0a930.png)

All the comments are incorporated. Please review.

2023-08-03 03:05 UTC, mkbansal1 approved these changes

2023-08-03 06:07 UTC, sselvara requested changes

2023-08-03 06:07 UTC, sselvara commented on styles/styles.css
> +    transform: translate(-50%, 0);
transform: translate(-50%, 0); seems duplicate as it is there in mobile css already.

2023-08-03 06:07 UTC, sselvara commented on scripts/delayed.js
> +    breakpoints.forEach((br, i) => {
use map function and join the source elements, and append once to avoid dom operation(appendChild) in loop.

2023-08-03 06:07 UTC, sselvara commented on scripts/delayed.js
> +    breakpoints.forEach((br, i) => {
use map function and join the source elements, and append once to avoid dom operation(appendChild) in loop.

2023-08-03 11:35 UTC, noormd08 commented on styles/styles.css
> +    transform: translate(-50%, 0);
Updated

2023-08-03 11:35 UTC, noormd08 commented on scripts/delayed.js
> +    breakpoints.forEach((br, i) => {
Updated

2023-08-03 11:36 UTC, noormd08 commented on scripts/delayed.js
> +    breakpoints.forEach((br, i) => {
Updated

2023-08-03 11:44 UTC, sselvara approved these changes

2023-08-03 13:04 UTC, merged