23-Accordion Implementation
hlxsites/fonterra-fernleaf pull request #62
Opened 2023-08-02 16:41 UTC by ParthasharathiB

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/
- After: https://<branch>--fonterra-fernleaf--hlxsites.hlx.page/

2023-08-03 05:57 UTC, mkbansal1 commented
@ParthasharathiB It seems like you are using 3 blocks:

1. Accordion - https://23-accordion--fonterra-fernleaf--hlxsites.hlx.page/en/products/yogurt
2. Accordion Panel - https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/accordion/nutrition-benefits
3. Table - https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/accordion/fernleaf-yogurt-plain

- Instead of an accordion panel, want we use a column block?
- Table block n accordion-panel blocks are used in authoring, but their block files (css/JS) are not added, due to which, we see 404 errors
<img width="1700" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/60f7439a-df20-4095-adf1-71b8fc5d268f">
- All css rules are added in accordion block, you should move table and accordion-panel css rules in respective blocks.
- Do you have example of multiple accordion group on same page?

2023-08-03 05:58 UTC, mkbansal1 requested changes
@ParthasharathiB Please implement the review comments

2023-08-03 05:58 UTC, mkbansal1 commented on blocks/accordion/accordion.css
> +@media (max-width: 900px) {
Avoid max-width, use mobile-first approach

2023-08-03 05:58 UTC, mkbansal1 commented on blocks/accordion/accordion.css
> +    .accordion-wrapper .table-wrapper .table.block:nth-child(1) {
Avoid max-width, use mobile-first approach

2023-08-03 05:58 UTC, mkbansal1 commented on blocks/accordion/accordion.js
> +      console.error('Could not load accordion content.', err);
Avoid console error

2023-08-03 05:58 UTC, mkbansal1 commented on blocks/header/header-backup
> +var div = document.createElement('div');
This seems to be an unwanted file, please remove it

2023-08-03 16:24 UTC, mkbansal1 commented on blocks/accordion/accordion.css
> +  color: var(--global-color-selective-yellow) !important;
Can we avoid `important`?

2023-08-03 16:25 UTC, mkbansal1 commented on blocks/header/header-backup
> +header .nav-wrapper {
@ParthasharathiB Remove this file

2023-08-03 16:27 UTC, mkbansal1 commented
Tables should break in 2 columns below 600px
<img width="621" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/b5520cc8-bf77-4dfe-a331-325f707cf50f">

2023-08-04 07:08 UTC, sselvara requested changes

2023-08-04 07:08 UTC, sselvara commented on blocks/table/table.css
> +    border-bottom: 1px solid #d3d3d3;
use color varaible.

2023-08-05 11:43 UTC, mkbansal1 approved these changes

2023-08-05 11:43 UTC, mkbansal1 commented
@ParthasharathiB This PR has merge conflict, please fix

2023-08-07 04:57 UTC, mkbansal1 approved these changes

2023-08-07 05:46 UTC, mkbansal1 approved these changes

2023-08-07 09:51 UTC, sselvara requested changes

2023-08-07 09:51 UTC, sselvara commented on blocks/accordion/accordion.css
> +  font-family: var(--global-quaternary-font-family);
font-family will not have any impact as font-family for header is added explicitly at line no:103, you can remove this or add font-family: var(--global-tertiary-font-family); here and remove line no:103.

2023-08-07 09:51 UTC, sselvara commented on blocks/accordion/accordion.css
> +.accordion-wrapper .accordion-section button[aria-expanded="false"]::after {
group below properties under after element like 
```
.accordion-wrapper .accordion-section button::after {
 right: auto;
  left: 0.625rem;
  color: var(--global-color-black);
  font-size: 1.25rem;
  font-weight: bold;
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  font-family: var(--global-georgia-font-family);
}
```

and keep only 

```
.accordion-wrapper .accordion-section button[aria-expanded="false"]::after {
 content: "\e922";
}

.accordion-wrapper .accordion-section button[aria-expanded="true"]::after {
 content: "\ e91e";
}
```

2023-08-07 09:51 UTC, sselvara commented on blocks/table/table.css
> +    margin-top: -12px;
avoid negative margin values.

2023-08-07 11:53 UTC, sselvara requested changes

2023-08-07 11:53 UTC, sselvara commented on blocks/table/table.css
> +    margin-top: -18px;
Add margin-bottom:0 for  `.accordion-wrapper .accordion-section button`, avoid negative margins.

2023-08-08 05:21 UTC, ParthasharathiB commented on blocks/table/table.css
> +    margin-top: -12px;
This one was added because of the table margin. P tag content Some of the tables we don't have, therefore I included this to ensure sustainability.

2023-08-08 08:40 UTC, sselvara commented
@ParthasharathiB accordion expand/collapse animation is missing in our implementation. Also '+', '-" icon size and content spacing is not matching with the original site.

2023-08-08 08:40 UTC, sselvara requested changes
@ParthasharathiB accordion expand/collapse animation is missing in our implementation. Also '+', '-" icon size and content spacing is not matching with the original site.

2023-08-09 05:07 UTC, sselvara commented
Created a new issue to track this https://github.com/hlxsites/fonterra-fernleaf/issues/92

> @ParthasharathiB accordion expand/collapse animation is missing in our implementation. Also '+', '-" icon size and content spacing is not matching with the original site.

2023-08-09 06:05 UTC, sselvara approved these changes

2023-08-09 06:07 UTC, merged