adding buy options block
hlxsites/fonterra-fernleaf pull request #69
Opened 2023-08-04 11:40 UTC by mkbansal1

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #61 

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.page/en/products/uht-milk
- After: https://61-buy-options--fonterra-fernleaf--hlxsites.hlx.live/en/products/uht-milk

2023-08-04 12:19 UTC, ujjwal5 commented
@mkbansal1 As discussed, we can reuse existing fetchplaceholders() from lib-franklin.js and pass getLanguage() as argument.
An example: https://github.com/hlxsites/fonterra-fernleaf/blob/main/scripts/modals/languages.js#L66

2023-08-04 12:21 UTC, mkbansal1 commented
> @mkbansal1 As discussed, we can reuse existing fetchplaceholders() from lib-franklin.js and pass getLanguage() as argument. An example: https://github.com/hlxsites/fonterra-fernleaf/blob/main/scripts/modals/languages.js#L66

Agree, i have reverted my logic

2023-08-04 12:33 UTC, ujjwal5 commented on blocks/buy-options/buy-options.js
> +    data.img = placeholder[`product${data.brand}`];
@mkbansal1 any specific reason why we have kept company images language specific?

2023-08-04 13:40 UTC, ParthasharathiB commented on blocks/buy-options/buy-options.js
> +    data.brand = row.children[0].innerText;
Include a null check on the children object

2023-08-04 14:03 UTC, mkbansal1 commented on blocks/buy-options/buy-options.js
> +    data.brand = row.children[0].innerText;
Done

2023-08-04 15:23 UTC, ujjwal5 commented on blocks/buy-options/buy-options.js
> +    data.img = placeholder[`product${data.brand}`];
Do we have a use case where we have different company image for different language. I think company logo/images is consistent across languages.
Using placeholder for this use case would be an overkill. Plus an author will have to maintain it at 2 different places(more chances of error). We can simply search/use ${data.brand} named image from images folder here.
WDYT ?

2023-08-04 17:05 UTC, sselvara requested changes

2023-08-05 12:01 UTC, mkbansal1 commented on blocks/buy-options/buy-options.js
> +    data.img = placeholder[`product${data.brand}`];
We are using placeholders to configure image paths (brand images, splash images ...), cant use sharefolder named based image as it does 301 redirect to media bus url.
Agree that it does not make sense to manage such images at two places, i have created a placeholder file at root level for such configurations.

2023-08-05 12:11 UTC, mkbansal1 commented on blocks/buy-options/buy-options.js
> +  buyOptions = [];
Done

2023-08-05 12:11 UTC, mkbansal1 commented on blocks/buy-options/buy-options.css
> +
Done

2023-08-07 07:04 UTC, ujjwal5 commented on blocks/buy-options/buy-options.js
> +    data.img = placeholder[`product${data.brand}`];
Should we remove these entries from placeholder files under /en and /ms ?

2023-08-07 07:58 UTC, mkbansal1 commented on blocks/buy-options/buy-options.js
> +    data.img = placeholder[`product${data.brand}`];
Already done

2023-08-07 08:33 UTC, ujjwal5 commented on blocks/buy-options/buy-options.js
> +    data.img = placeholder[`product${data.brand}`];
Thanks I see we have removed it now.

2023-08-07 08:34 UTC, ujjwal5 approved these changes

2023-08-07 09:06 UTC, sselvara approved these changes

2023-08-07 09:09 UTC, merged