Code refactoring - removed decorateIcon call
hlxsites/fonterra-fernleaf pull request #71
Opened 2023-08-04 13:53 UTC by mkbansal1

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #64 

Test URLs:
- Before: https://main--fonterra-fernleaf--hlxsites.hlx.live/en
- After: https://64-performance-issues--fonterra-fernleaf--hlxsites.hlx.live/en

2023-08-04 15:35 UTC, ujjwal5 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
I believe we would need this, currently on opening dialog background is too bright.
Added this deliberately to have look and feel same as of live site.

2023-08-05 12:29 UTC, mkbansal1 commented on styles/lazy-styles.css
> +@media (min-width: 900px) {
we are using Franklin standard view ports.

2023-08-05 12:51 UTC, mkbansal1 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
Changing bg color to black distort the experience 
<img width="1565" alt="image" src="https://github.com/hlxsites/fonterra-fernleaf/assets/129100763/f669e4da-a5e8-4bfd-a531-eada5357af51">

2023-08-07 06:57 UTC, ujjwal5 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
I'm not getting this experience, can you check with latest main branch ?

2023-08-07 06:58 UTC, ujjwal5 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
@sselvara can you please confirm as well ?

2023-08-07 06:59 UTC, mkbansal1 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
@ujjwal5 seems like you have tested on home page only, check this page
https://main--fonterra-fernleaf--hlxsites.hlx.live/en/recipes

2023-08-07 08:37 UTC, ujjwal5 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
correct, in other pages the behaviour is same as you mentioned.
Can you fix this to make the experience same as it's there in live site.?

2023-08-07 08:40 UTC, mkbansal1 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
Removing bg color is the fix. otherwise we have to add additional div in modal, which will bring black bg color. I will avoid that change for now.

2023-08-07 08:58 UTC, ujjwal5 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
Let's set following css in lazy-styles.css

main {
  background-color: white;
}

This should fix the problem and be in sync with live site. @mkbansal1 can you try this ?

2023-08-07 09:03 UTC, mkbansal1 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
This wont fix the issue, as main bg will override body bg.
also, lets have a separate card to fix it. This is a performance card, i saw this P1 issue to revert it.
@ujjwal5  Please create a card in backlog for it.

2023-08-07 09:11 UTC, ujjwal5 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
sure, will create once this is merged.

2023-08-07 09:25 UTC, sselvara requested changes

2023-08-07 09:25 UTC, sselvara commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
@ujjwal5, can we set the background to the selector `dialog::backdrop` instead of body to fix this problem?

https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop?retiredLocale=en

2023-08-07 09:31 UTC, ujjwal5 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
Tried adding this. This too creates a black background in other pages as @mkbansal1 had mentioned. Anyway let me create a issue for this and unblock this pr if other comments are resolved.

2023-08-07 09:32 UTC, sselvara approved these changes

2023-08-07 09:32 UTC, ujjwal5 commented on styles/lazy-styles.css
> -  background-color: var(--global-color-black);
Created: https://github.com/hlxsites/fonterra-fernleaf/issues/77

2023-08-07 09:33 UTC, merged